### ISSUE TITLE
Create simple search python website for this 

### ISSUE THREAD

**Issue by PatelUtkarsh** [PatelUtkarsh/awesomedl-cli#1]
Create python website that fetch all links and displays it with epi name. 

We already have function which gives name and urls.

**Comment by PareshRadadiya** [comment]
@PatelUtkarsh 

Could you let me know site URL?

**Comment by PatelUtkarsh** [comment]
It's not gonna happen, check https://github.com/PatelUtkarsh/awesomedl-cli/blob/master/README.md
